project:
  type: website
  output-dir: docs
website:
  title: "⌂"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Sanjuvi/
      - icon: linkedin
        href: https://www.linkedin.com/in/sanjeevi-%E0%AE%9A%E0%AE%9E%E0%AF%8D%E0%AE%9A%E0%AF%80%E0%AE%B5%E0%AE%BF-01a7b813b/
format:
  html:
    theme: darkly
    css: styles.css



